[project]
name = "tibber-dashboard-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.5",
    "lxml>=5.3.0",
    "requests>=2.32.3",
]
